trigger:
- master   # run pipeline when master branch is updated

pool:
  name: Rutu   # your self-hosted agent pool

steps:
- checkout: self   # download your repo first

# Install Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

# Build React frontend
- script: |
    cd sales-frontend
    npm install
    npm run build
  displayName: 'npm install and build React frontend'

# Copy React build folder to artifacts staging directory
- task: CopyFiles@2
  inputs:
    SourceFolder: 'sales-frontend/build'
    Contents: '**/*'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy React build artifacts'

# Publish build artifacts
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish build artifacts'

# ✅ Deploy to Azure Web App
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'MyAzureConnection'   # service connection name
    appName: 'my-react-webapp'               # your Web App name
    package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
  displayName: 'Deploy React app to Azure WebApp'

