trigger:
- master

pool:
  name: supriya

steps:
- checkout: self   # ✅ download your repo first

- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    cd sales-frontend/src
    npm install
    npm run build
  displayName: 'npm install and build'

